@host = http://localhost:8080
@powerStation = {{host}}/api/powerStations

GET {{powerStation}}

###
GET {{powerStation}}/2

###
POST {{powerStation}}
Content-Type: application/json

{
    "name": "Battery Storage Charlie",
    "status": "Critical"
}

###
PUT {{powerStation}}/2
Content-Type: application/json

{
    "name": "Battery Storage Charlie",
    "status": "OK"
}

###
DELETE {{powerStation}}/3